1.Create a 1D NumPy array of numbers from 0 to 9.

In [2]:
import numpy as np

In [3]:
Arr =np.array([0,1,2,3,4,5,6,7,8,9])
Arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2.Create a 2D array of shape (3, 3) with all elements as 1.

In [4]:
Arr2=np.array([1,1,1,1,1,1,1,1,1]).reshape(3,3)
Arr2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

3.Generate a NumPy array of 15 random integers between 10 and 50.

In [5]:
Arr3=([45,46,27,22,18,15,26,33,10,49,42,43,28,6,31,])
Arr3

[45, 46, 27, 22, 18, 15, 26, 33, 10, 49, 42, 43, 28, 6, 31]

4.Create an array of 5 evenly spaced numbers between 0 and 1 (inclusive).

In [7]:
Arr4 =np.array([0.0,0.2,0.4,0.6,0.8])
Arr4

array([0. , 0.2, 0.4, 0.6, 0.8])

5.Create a 4x4 identity matrix using NumPy.

In [10]:
arl=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
Arr5 =arl.reshape(4,4)
Arr5

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

6.Create an array from the list [10, 20, 30, 40] and change the data type to float.

In [11]:
list =[10,20,30,40]
Arr6=np.array(list,dtype=np.float32)
Arr6

array([10., 20., 30., 40.], dtype=float32)

7.Create a 3x3 array with values from 1 to 9, then extract the second column.

In [15]:
Arr7=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
second_col =Arr7[:1]
print("First column",Arr7)
print("Second column",second_col)

First column [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second column [[1 2 3]]


8.Create a 1D array with 10 elements and reshape it into a 2x5 matrix.

In [17]:
Arr8=np.array([11,22,33,44,55,66,77,88,99,00]).reshape(2,5)
Arr8

array([[11, 22, 33, 44, 55],
       [66, 77, 88, 99,  0]])

9.Create two 2x2 matrices and perform matrix multiplication.

In [18]:
matri =np.array([45,18,27,28]).reshape(2,2)
matri*2

array([[90, 36],
       [54, 56]])

In [19]:
matri*1.2

array([[54. , 21.6],
       [32.4, 33.6]])

10.Given the array arr = np.array([5, 12, 7, 18, 3]), replace all values greater than 10 with 100.

In [22]:
  Arr10 = np.array([5, 12, 7, 18, 3])
Arr10[Arr10>10]=100